#!/usr/bin/env bash

sudo apt update && sudo apt upgrade && sudo apt install -f $(grep -vE "^\s*#" packages  | tr "\n" " ")

cp vimrc ~/.vimrc
cp gvimrc ~/.gvimrc
cp cvimrc ~/.cvimrc
cp bashrc ~/.bashrc
cp inputrc ~/.inputrc

mkdir ~/.i3
cp i3 ~/.i3/config
cp i3status ~/.i3/i3status

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mkdir ~/.vim/tmp

mkdir ~/.bin