#!/usr/bin/env bash

cp vimrc ~/.vimrc
cp gvimrc ~/.gvimrc
cp cvimrc ~/.cvimrc
cp bashrc ~/.bashrc
cp inputrc ~/.inputrc
cp Xdefaults ~/.Xdefaults

mkdir ~/.i3
cp i3 ~/.i3/config
cp i3status ~/.i3/i3status.conf

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mkdir ~/.vim/tmp

mkdir ~/.bin